// lib/features/roadmap/screens/roadmap_screen.dart
//
// MY ROADMAP — fully personalised.
// The journey is generated by roadmap_engine.dart from:
//   • the career the user picks (defaults to their #1 match)
//   • their school year (past stages tick off, current stage says NOW)
//   • their preferred pathway (their route floats to Option A with a ⭐)
// A Software Engineer's roadmap looks nothing like a Nurse's — different
// milestones, different routes, different colours.

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:supabase_flutter/supabase_flutter.dart' hide Provider;
import '../../../core/constants/app_constants.dart';
import '../../../core/services/providers.dart';
import '../../../core/theme/app_theme.dart';
import '../../../shared/models/models.dart';
import '../../../shared/widgets/shared_widgets.dart';
import '../roadmap_engine.dart';

class RoadmapScreen extends ConsumerWidget {
  const RoadmapScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final matchesAsync = ref.watch(matchesProvider);
    final user         = ref.watch(appUserProvider).valueOrNull;
    final prefs        = ref.watch(preferencesProvider).valueOrNull;
    final careers      = ref.watch(allCareersProvider).valueOrNull ?? const <Career>[];
    final isPremium    = ref.watch(isPremiumProvider).valueOrNull ?? false;

    return Scaffold(
      backgroundColor: AppColors.bgPage,
      body: SafeArea(child: matchesAsync.when(
        loading: () => const Center(child: CircularProgressIndicator()),
        error: (e, _) => ErrorView(message: e.toString()),
        data: (matches) {
          if (matches.isEmpty) {
            return Center(child: EmptyState(
              emoji: '🗺️', title: 'No roadmap yet',
              subtitle: 'Complete onboarding and we\'ll build a personalised journey to your top career.',
              actionLabel: 'Get Started',
              onAction: () => context.push(AppConstants.routeWhoAreYou)));
          }

          // ── Which career is the roadmap for? ──
          final selectedId = ref.watch(roadmapCareerIdProvider);
          final match = matches.firstWhere(
            (m) => m.careerId == selectedId,
            orElse: () => matches.first);

          // Category lookup (matches don't carry it)
          final career = careers.where((c) => c.id == match.careerId).firstOrNull;

          final schoolYear = (user?.schoolYear ?? 'Year 11').trim();
          final pathway = (prefs?['pathway_focus'] as String?)?.trim();

          final roadmap = buildCareerRoadmap(
            careerName: match.careerName,
            category: career?.category,
            schoolYear: schoolYear,
            preferredPathway: pathway);

          return SingleChildScrollView(
            padding: const EdgeInsets.all(20),
            child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [

              // ── Header ────────────────────────────────────
              Text('My Roadmap 🗺️',
                style: Theme.of(context).textTheme.displayMedium),
              const SizedBox(height: 4),
              Text(
                'Built for ${user?.firstName ?? 'you'} · $schoolYear'
                '${pathway != null && pathway.isNotEmpty && pathway != 'Both' ? ' · $pathway route' : ''}',
                style: const TextStyle(fontFamily: 'Nunito', fontSize: 13,
                  color: AppColors.textMid, fontWeight: FontWeight.w600)),

              const SizedBox(height: 16),

              // ── Career switcher (from YOUR matches) ───────
              SizedBox(height: 44, child: ListView.separated(
                scrollDirection: Axis.horizontal,
                itemCount: matches.take(6).length,
                separatorBuilder: (_, __) => const SizedBox(width: 8),
                itemBuilder: (_, i) {
                  final m = matches[i];
                  final sel = m.careerId == match.careerId;
                  final mCareer = careers.where((c) => c.id == m.careerId).firstOrNull;
                  final (chipColor, chipEmoji) =
                      roadmapThemeFor(mCareer?.category, m.careerName);
                  return GestureDetector(
                    onTap: () => ref.read(roadmapCareerIdProvider.notifier)
                        .state = m.careerId,
                    child: AnimatedContainer(
                      duration: const Duration(milliseconds: 180),
                      padding: const EdgeInsets.symmetric(
                        horizontal: 14, vertical: 8),
                      decoration: BoxDecoration(
                        color: sel ? chipColor : AppColors.bgCard,
                        borderRadius: BorderRadius.circular(12),
                        border: Border.all(
                          color: sel ? chipColor : AppColors.border)),
                      child: Row(children: [
                        Text(chipEmoji, style: const TextStyle(fontSize: 15)),
                        const SizedBox(width: 6),
                        Text(m.careerName, style: TextStyle(
                          fontFamily: 'Nunito', fontSize: 12.5,
                          fontWeight: FontWeight.w800,
                          color: sel ? Colors.white : AppColors.textMid)),
                      ]),
                    ));
                })),

              const SizedBox(height: 20),

              // ── Hero for the selected career ──────────────
              Container(
                padding: const EdgeInsets.all(18),
                decoration: BoxDecoration(
                  gradient: LinearGradient(colors: [
                    roadmap.color, roadmap.color.withOpacity(0.75)]),
                  borderRadius: BorderRadius.circular(18)),
                child: Row(children: [
                  Text(roadmap.emoji, style: const TextStyle(fontSize: 34)),
                  const SizedBox(width: 14),
                  Expanded(child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start, children: [
                    const Text('YOUR PATH TO', style: TextStyle(
                      fontFamily: 'Nunito', fontSize: 10,
                      fontWeight: FontWeight.w800, color: Colors.white70,
                      letterSpacing: 1.2)),
                    Text(match.careerName, style: const TextStyle(
                      fontFamily: 'Nunito', fontSize: 19,
                      fontWeight: FontWeight.w900, color: Colors.white)),
                  ])),
                  MatchRing(pct: match.matchScore, size: 44),
                ])),

              const SizedBox(height: 24),

              // ── The personalised journey ──────────────────
              const SectionHeader(title: 'Your Learning Journey'),
              const SizedBox(height: 16),
              ...roadmap.stages.map((s) => _StageItem(stage: s,
                color: roadmap.color)),

              // ── Age-18 route branch ───────────────────────
              Padding(
                padding: const EdgeInsets.only(top: 4, bottom: 12),
                child: Row(children: [
                  Container(width: 36, height: 36,
                    decoration: BoxDecoration(
                      color: roadmap.color.withOpacity(0.15),
                      shape: BoxShape.circle,
                      border: Border.all(color: roadmap.color, width: 2)),
                    child: const Center(child: Text('🎯',
                      style: TextStyle(fontSize: 16)))),
                  const SizedBox(width: 14),
                  Expanded(child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start, children: [
                    Text('${roadmap.branchYear}', style: TextStyle(
                      fontFamily: 'Nunito', fontSize: 11,
                      fontWeight: FontWeight.w800, color: roadmap.color,
                      letterSpacing: 0.5)),
                    const Text('Age 18 — choose your route', style: TextStyle(
                      fontFamily: 'Nunito', fontSize: 14,
                      fontWeight: FontWeight.w800)),
                  ])),
                ])),
              ...roadmap.routes.asMap().entries.map((e) => _RouteCard(
                letter: String.fromCharCode(65 + e.key), // A, B, C
                option: e.value)),

              const SizedBox(height: 8),
              // Compare the routes side by side (Premium)
              EduCard(
                color: AppColors.primaryPale,
                onTap: () => isPremium
                    ? context.push('${AppConstants.routeCompare}?career=${match.careerId}')
                    : context.push(AppConstants.routePricing),
                child: Row(children: [
                  const Text('⚖️', style: TextStyle(fontSize: 20)),
                  const SizedBox(width: 12),
                  Expanded(child: Row(children: [
                    const Text('Compare these routes side by side',
                      style: TextStyle(fontFamily: 'Nunito', fontSize: 13.5,
                        fontWeight: FontWeight.w800)),
                    if (!isPremium) ...[
                      const SizedBox(width: 6),
                      const Icon(Icons.lock_rounded, size: 14,
                        color: AppColors.textLight),
                    ],
                  ])),
                  const Icon(Icons.chevron_right_rounded,
                    color: AppColors.primary),
                ])),

              const SizedBox(height: 16),

              // ── Final destination ─────────────────────────
              _StageItem(stage: roadmap.finalStage, color: roadmap.color,
                isLast: true),

              const SizedBox(height: 20),

              // ── Full qualification browser (Premium) ──────
              const SectionHeader(title: 'All Qualifications 📋'),
              const SizedBox(height: 8),
              const Text('Browse every GCSE, A-Level, BTEC and T-Level.',
                style: TextStyle(fontFamily: 'Nunito', fontSize: 13,
                  color: AppColors.textMid)),
              const SizedBox(height: 12),
              if (isPremium)
                _FullQualBrowser()
              else
                const PremiumLock(title: 'All Qualifications',
                  subtitle: 'Browse every GCSE, A-Level, BTEC and T-Level — Premium only.'),

              const SizedBox(height: 24),

              // ── Notifications ─────────────────────────────
              EduCard(
                color: AppColors.primaryPale,
                onTap: () => context.push(AppConstants.routeNotifications),
                child: const Row(children: [
                  Text('🔔', style: TextStyle(fontSize: 20)),
                  SizedBox(width: 12),
                  Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                    Text('Upcoming Deadlines', style: TextStyle(fontFamily: 'Nunito',
                      fontSize: 14, fontWeight: FontWeight.w800)),
                    Text('UCAS deadline — 25 Jan | Apprenticeship applications open',
                      style: TextStyle(fontFamily: 'Nunito', fontSize: 12,
                        color: AppColors.textMid)),
                  ])),
                  Icon(Icons.chevron_right_rounded, color: AppColors.primary),
                ]),
              ),
              const SizedBox(height: 80),
            ]),
          );
        },
      )),
    );
  }
}

// ── Timeline stage widget ──────────────────────────────────────
class _StageItem extends StatelessWidget {
  final RoadmapStage stage;
  final Color color;
  final bool isLast;
  const _StageItem({required this.stage, required this.color,
    this.isLast = false});

  @override
  Widget build(BuildContext context) {
    final nodeColor = stage.done ? AppColors.success : color;
    return Row(crossAxisAlignment: CrossAxisAlignment.start, children: [
      Column(children: [
        Container(width: 36, height: 36,
          decoration: BoxDecoration(
            color: stage.current
                ? nodeColor
                : nodeColor.withOpacity(0.15),
            shape: BoxShape.circle,
            border: Border.all(color: nodeColor, width: 2)),
          child: Center(child: stage.done
              ? const Icon(Icons.check_rounded, size: 18, color: AppColors.success)
              : Text(stage.emoji, style: const TextStyle(fontSize: 16)))),
        if (!isLast)
          Container(width: 2, height: 76, color: nodeColor.withOpacity(0.25)),
      ]),
      const SizedBox(width: 14),
      Expanded(child: Padding(
        padding: const EdgeInsets.only(top: 2, bottom: 18),
        child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
          Row(children: [
            Text(stage.timeLabel, style: TextStyle(
              fontFamily: 'Nunito', fontSize: 11,
              fontWeight: FontWeight.w800, color: nodeColor,
              letterSpacing: 0.5)),
            if (stage.current) ...[
              const SizedBox(width: 8),
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
                decoration: BoxDecoration(color: nodeColor,
                  borderRadius: BorderRadius.circular(999)),
                child: const Text('YOU ARE HERE', style: TextStyle(
                  fontFamily: 'Nunito', fontSize: 9,
                  fontWeight: FontWeight.w900, color: Colors.white,
                  letterSpacing: 0.6))),
            ],
            if (stage.done) ...[
              const SizedBox(width: 8),
              const TagBadge(label: '✓ Done',
                bg: Color(0xFFECFDF5), fg: Color(0xFF065F46)),
            ],
          ]),
          const SizedBox(height: 4),
          Text(stage.title, style: const TextStyle(fontFamily: 'Nunito',
            fontSize: 14.5, fontWeight: FontWeight.w800)),
          const SizedBox(height: 6),
          ...stage.milestones.map((m) => Padding(
            padding: const EdgeInsets.only(bottom: 4),
            child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [
              Text('→ ', style: TextStyle(fontFamily: 'Nunito',
                fontSize: 12, fontWeight: FontWeight.w800, color: nodeColor)),
              Expanded(child: Text(m, style: const TextStyle(
                fontFamily: 'Nunito', fontSize: 12.5,
                color: AppColors.textMid, height: 1.45))),
            ]))),
        ]),
      )),
    ]);
  }
}

// ── Age-18 route option card ───────────────────────────────────
class _RouteCard extends StatelessWidget {
  final String letter;
  final RouteOption option;
  const _RouteCard({required this.letter, required this.option});

  @override
  Widget build(BuildContext context) => Padding(
    padding: const EdgeInsets.only(bottom: 10, left: 50),
    child: Container(
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: AppColors.bgCard,
        borderRadius: BorderRadius.circular(14),
        border: Border.all(
          color: option.preferred ? option.color : AppColors.border,
          width: option.preferred ? 2 : 1.5)),
      child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [
        Container(width: 5, height: 64,
          decoration: BoxDecoration(color: option.color,
            borderRadius: BorderRadius.circular(3))),
        const SizedBox(width: 12),
        Expanded(child: Column(
          crossAxisAlignment: CrossAxisAlignment.start, children: [
          Row(children: [
            Text('${option.emoji} Option $letter — ${option.title}',
              style: const TextStyle(fontFamily: 'Nunito', fontSize: 13.5,
                fontWeight: FontWeight.w800)),
          ]),
          const SizedBox(height: 2),
          Row(children: [
            TagBadge(label: option.duration,
              bg: option.color.withOpacity(0.12), fg: option.color),
            if (option.preferred) ...[
              const SizedBox(width: 6),
              const TagBadge(label: '⭐ Your pick',
                bg: Color(0xFFFFFBEB), fg: Color(0xFF92400E)),
            ],
          ]),
          const SizedBox(height: 6),
          Text(option.detail, style: const TextStyle(fontFamily: 'Nunito',
            fontSize: 12, color: AppColors.textMid, height: 1.45)),
        ])),
      ]),
    ));
}

// ── Full qualification browser (Premium) — unchanged behaviour ─
class _FullQualBrowser extends ConsumerStatefulWidget {
  @override
  ConsumerState<_FullQualBrowser> createState() => _FullQualBrowserState();
}

class _FullQualBrowserState extends ConsumerState<_FullQualBrowser> {
  String _type = 'GCSE';
  String _search = '';
  List<Map<String, dynamic>>? _preclasses;

  @override
  void initState() {
    super.initState();
    _load();
  }

  Future<void> _load() async {
    final res = await Supabase.instance.client
        .from('preclass').select().order('type').order('title');
    if (mounted) setState(() => _preclasses = (res as List).cast<Map<String, dynamic>>());
  }

  @override
  Widget build(BuildContext context) {
    final types = ['GCSE', 'A-Level', 'BTEC', 'T-Level'];
    final typeEmojis = {'GCSE': '📗', 'A-Level': '📘', 'BTEC': '📙', 'T-Level': '📕'};
    var filtered = _preclasses?.where((p) => p['type'] == _type).toList() ?? [];
    if (_search.isNotEmpty) {
      filtered = filtered.where((p) => (p['title'] ?? '').toString()
          .toLowerCase().contains(_search.toLowerCase())).toList();
    }

    return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
      SingleChildScrollView(
        scrollDirection: Axis.horizontal,
        child: Row(children: types.map((t) => Padding(
          padding: const EdgeInsets.only(right: 8),
          child: GestureDetector(
            onTap: () => setState(() => _type = t),
            child: AnimatedContainer(
              duration: const Duration(milliseconds: 180),
              padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 8),
              decoration: BoxDecoration(
                color: _type == t ? AppColors.primary : AppColors.bgCard,
                borderRadius: BorderRadius.circular(10),
                border: Border.all(
                  color: _type == t ? AppColors.primary : AppColors.border)),
              child: Text('${typeEmojis[t]} $t', style: TextStyle(
                fontFamily: 'Nunito', fontSize: 12, fontWeight: FontWeight.w700,
                color: _type == t ? Colors.white : AppColors.textMid)),
            ),
          ),
        )).toList()),
      ),
      const SizedBox(height: 12),
      // Search bar — browse and filter every qualification of this type
      TextField(
        onChanged: (v) => setState(() => _search = v),
        decoration: InputDecoration(
          hintText: 'Search ${_type}s...',
          prefixIcon: const Icon(Icons.search_rounded, size: 18),
          contentPadding: const EdgeInsets.symmetric(vertical: 10))),
      const SizedBox(height: 12),
      if (_preclasses == null)
        const Center(child: CircularProgressIndicator())
      else if (filtered.isEmpty)
        const EmptyState(emoji: '🔍', title: 'Nothing found',
          subtitle: 'Try a different search term')
      else
        ...filtered.map((p) => _PreclassTile(p)),
    ]);
  }
}

class _PreclassTile extends ConsumerStatefulWidget {
  final Map<String, dynamic> preclass;
  const _PreclassTile(this.preclass);
  @override
  ConsumerState<_PreclassTile> createState() => _PreclassTileState();
}

class _PreclassTileState extends ConsumerState<_PreclassTile> {
  bool _expanded = false;
  List<Map<String, dynamic>>? _linkedCourses;

  Future<void> _loadCourses() async {
    if (_linkedCourses != null) return;
    final res = await Supabase.instance.client
        .from('preclass_course')
        .select('to_course, courses(id, title, institutions(name))')
        .eq('from_preclass', widget.preclass['id']);
    // Deduplicate courses
    final seen = <String>{};
    final unique = <Map<String, dynamic>>[];
    for (final e in (res as List)) {
      final course = e['courses'] as Map<String, dynamic>;
      final id = course['id'] as String;
      if (!seen.contains(id)) {
        seen.add(id);
        unique.add(course);
      }
    }
    if (mounted) setState(() => _linkedCourses = unique);
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8),
      child: EduCard(
        onTap: () async {
          setState(() => _expanded = !_expanded);
          if (_expanded) await _loadCourses();
        },
        child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
          Row(children: [
            Container(width: 8, height: 8,
              decoration: const BoxDecoration(color: AppColors.primary, shape: BoxShape.circle)),
            const SizedBox(width: 10),
            Expanded(child: Text(widget.preclass['title'] ?? '',
              style: const TextStyle(fontFamily: 'Nunito',
                fontSize: 13, fontWeight: FontWeight.w700))),
            TagBadge(label: widget.preclass['level'] ?? '',
              bg: AppColors.primaryPale, fg: AppColors.primaryDark),
            const SizedBox(width: 6),
            Icon(_expanded ? Icons.expand_less : Icons.expand_more,
              size: 18, color: AppColors.textLight),
          ]),
          if (_expanded) ...[
            const SizedBox(height: 10),
            const Text('Leads to these courses:',
              style: TextStyle(fontFamily: 'Nunito', fontSize: 11,
                color: AppColors.textMid, fontWeight: FontWeight.w700)),
            const SizedBox(height: 6),
            if (_linkedCourses == null)
              const Center(child: CircularProgressIndicator())
            else if (_linkedCourses!.isEmpty)
              const Text('No direct course links yet.',
                style: TextStyle(fontFamily: 'Nunito', fontSize: 12,
                  color: AppColors.textLight))
            else ..._linkedCourses!.map((c) => Padding(
              padding: const EdgeInsets.only(bottom: 4),
              child: GestureDetector(
                onTap: () => context.push('/course/${c['id']}'),
                child: Row(children: [
                  const Text('→ ', style: TextStyle(color: AppColors.primary,
                    fontSize: 12, fontWeight: FontWeight.w700)),
                  Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                    Text(c['title'] ?? '', style: const TextStyle(
                      fontFamily: 'Nunito', fontSize: 12,
                      fontWeight: FontWeight.w700, color: AppColors.primary)),
                    if (c['institutions'] != null)
                      Text((c['institutions'] as Map)['name'] ?? '',
                        style: const TextStyle(fontFamily: 'Nunito',
                          fontSize: 11, color: AppColors.textMid)),
                  ])),
                ]),
              ),
            )),
          ],
        ]),
      ),
    );
  }
}

class RoadmapPlanScreen extends StatelessWidget {
  const RoadmapPlanScreen({super.key});
  @override
  Widget build(BuildContext context) => Scaffold(
    backgroundColor: AppColors.bgPage,
    appBar: AppBar(
      title: const Text('My Learning Roadmap'),
      leading: GestureDetector(onTap: () => context.pop(), child: const BackBtn()),
      actions: [IconButton(
        icon: const Icon(Icons.home_rounded),
        tooltip: 'Dashboard',
        onPressed: () => context.go('/home'))]),
    body: const Center(child: Text('Roadmap editor coming soon! 🚀',
      style: TextStyle(fontFamily: 'Nunito', fontSize: 16))));
}
